[package]

name = "packr-rs"
version = "0.0.1"
authors = ["Daniel Ludwig <codi@code-disaster.com>"]

build = "build.rs"

[dependencies]
rustc-serialize = "0.2.7"

[dependencies.jni]
git = "http://github.com/code-disaster/jni-rs"
