[package]

name = "packr-rs"
version = "0.0.2"
authors = ["Daniel Ludwig <codi@code-disaster.com>"]

build = "build.rs"

[dependencies]
getopts = "0.2.11"
rustc-serialize = "0.3.15"

[dependencies.jni]
git = "http://github.com/code-disaster/jni-rs"
